services:
  vekolom:
    build:
      context: .
      target: dev
    command: >
      bash -lc "
        python utils/wait-for-services.py &&
        uvicorn app.main:app --host ${APP_HOST} --port ${APP_PORT} --reload
      "
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - default
      - vekolom-service-network

  celery_vekolom:
    build:
      context: .
      target: dev
    networks:
      - default
      - vekolom-service-network

  celery_backup_vekolom:
    build:
      context: .
      target: dev
    networks:
      - default
      - vekolom-service-network

  celery_beat_vekolom:
    build:
      context: .
      target: dev
    networks:
      - default
      - vekolom-service-network

  frontend_vekolom:
    build:
      context: ./frontend
    container_name: frontend_vekolom
    command: sh -c "npm run dev -- --host 0.0.0.0 --port ${FRONTEND_PORT}"
    env_file:
      - .env
    environment:
      CHOKIDAR_USEPOLLING: "true"
      FRONTEND_HMR_HOST: ${FRONTEND_HMR_HOST}
      FRONTEND_HMR_PORT: ${FRONTEND_HMR_PORT}
      FRONTEND_HMR_PROTOCOL: ${FRONTEND_HMR_PROTOCOL}
    volumes:
      - ./frontend:/frontend
      - frontend_node_modules:/frontend/node_modules
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    networks:
      - default
      - vekolom-service-network

volumes:
  frontend_node_modules:

networks:
  default:
    driver: bridge

  vekolom-service-network:
    name: vekolom-service-network
    external: true
